# Generated by Django 4.2.2 on 2023-07-14 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('autor', models.CharField(max_length=20)),
                ('titulo', models.CharField(max_length=100)),
                ('descricao', models.CharField(max_length=2000)),
                ('link', models.URLField(blank=True, max_length=100, null=True)),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='blog/')),
            ],
        ),
    ]
