# Generated by Django 4.2.2 on 2023-07-17 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_contacto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Projeto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('repo_link', models.URLField(max_length=500)),
                ('descricao', models.CharField(max_length=2000)),
            ],
        ),
    ]
