# Generated by Django 4.2.2 on 2023-07-19 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_post_dislike_post_like_comentario'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tecnologia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('repo_link', models.URLField(max_length=500)),
                ('descricao', models.CharField(max_length=2000)),
            ],
        ),
    ]
