# Generated by Django 4.2.2 on 2023-07-19 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0006_rename_repo_link_projeto_source_code_projeto_website'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projeto',
            old_name='source_code',
            new_name='repo_link',
        ),
        migrations.RenameField(
            model_name='tecnologia',
            old_name='repo_link',
            new_name='source_code',
        ),
        migrations.RemoveField(
            model_name='projeto',
            name='website',
        ),
        migrations.AddField(
            model_name='tecnologia',
            name='website',
            field=models.URLField(default='https://github.com', max_length=500),
            preserve_default=False,
        ),
    ]
