# Generated by Django 4.2.2 on 2023-07-19 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0007_rename_source_code_projeto_repo_link_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Docente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Disciplina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('ano', models.IntegerField(default=1)),
                ('semestre', models.IntegerField(default=1)),
                ('ECTS', models.IntegerField(default=0)),
                ('docentes', models.ManyToManyField(to='portfolio.docente')),
            ],
        ),
    ]
